server:
  port: 9086
  servlet:
    context-path: /

spring:
  profiles:
    active: @active.profiles@
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=Test01
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug

---
spring:
  profiles: dev
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=Test01
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
---
spring:
  profiles: prod
  datasource:
    url: jdbc:sqlserver://srv-rahkaran;databaseName=firmco_sg3
    username: Shasta
    password: Hello@#@#123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
